version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-west-2"
    CODEDEPLOY_APPLICATION_NAME: "lambda-app"
    CODEDEPLOY_DEPLOYMENT_GROUP: "lambda-group"
    LAMBDA_ALIAS: "live"
    LAMBDA_EXEC_ROLE_ARN: "arn:aws:iam::<account-id>:role/<lambda-execution-role>"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing AWS CLI and dependencies"
      - pip install --upgrade pip
      - pip install awscli --upgrade

  build:
    commands:
      - echo "=== Running Lambda Deployment Script ==="
      - chmod +x scripts/deploy_lambdas.sh
      - ./scripts/deploy_lambdas.sh

  post_build:
    commands:
      - echo "=== Lambda Deployment Completed Successfully ==="

artifacts:
  files:
    - appspec.yml
